[tool.poetry]
name = "SMorph"
version = "0.1.0"
description = "A library for rapid analysis of the morphology of cells of the nervous system."
authors = ["Parul Sethi <parul1sethi@gmail.com>", "Kushaan Gupta <gkushaan@rediffmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
jupyter = "^1.0.0"
matplotlib = "^3.3.2"
networkx = "^2.5"
numpy = "^1.19.2"
scikit-image = "^0.17.2"
scikit-learn = "^0.23.2"
scipy = "^1.5.2"
skan = "^0.8"
numba = "^0.51.2"
pandas = "^1.1.2"
seaborn = "^0.11.0"
ipyvolume = "^0.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
